import { type NextPage } from "next";
import Head from "next/head";
import { Layout } from "src/layouts/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Anonymous Questions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <header className="p-4">
          <h1>GIVEAWAY</h1>
        </header>
      </Layout>
    </>
  );
};

export default Home;
